### ISSUE TITLE
Error after updating to version 1.2.33

### ISSUE THREAD

**Issue by denisvitez** [trela-official/rabbitmq-pika-flask#67]
I am encountering the following error after updating from 1.2.15 - 1.2.33

`AttributeError: 'RabbitMQ' object has no attribute 'development'`

The error is inside RabbitMQ.py, line 203 in decorator

`if not self.development or os.getenv("WERKZEUG_RUN_MAIN") == "true":`

It seems that the `queue` decorator inside my `flask-restx` controller gets called before the `__init` method inside `RabbitMQ.py` and because of that the `self.development` property is not yet available at the time. Setting the initial value `development = None` inside the RabbitMQ class solves the issue.

```
class RabbitMQ:
    """Main class containing queue and message sending methods"""

    app: Flask
    config: Config

    get_connection: Callable[[], BlockingConnection]
    consumers: set
    development: bool or None

    body_parser: Callable or None
    msg_parser: Callable or None

    exchange_name: str
    exchange_params: ExchangeParams

    queue_prefix: str
    queue_params: QueueParams

    on_message_error_callback: Union[MessageErrorCallback, None]
    middlewares: List[RabbitConsumerMiddleware]

    # This solves the issue
    development = None

    def __init__(
```

**Comment by rafaelclp** [comment]
Thanks for the report, I fixed it in #70 

This lib is not being actively developed anymore as we only have some legacy services using it, but if you find another bug feel free to open an issue and I will look into it eventually.
